chore(core): augmentations should use relative import (#26364)
Previously (accidentally) used the module name as a name for the import. This caused the build to fail with `error TS5055: Cannot write file 'aws-cdk-lib/aws-cloudwatch/index.d.ts' because it would overwrite input file.` Also exclude declaration files from the build, which makes it slightly faster (~20s).

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*