docs(step-functions): fix item reader path code snippet
Following errors are detected by CodeBuild logs, hence, changes resolve these.
```
aws-cdk-lib.aws_stepfunctions-README-L589.ts:34:1 - error TS2304: Cannot find name 'distributedMap'.

34 distributedMap.itemProcessor(new sfn.Pass(this, 'Pass State'));
   ~~~~~~~~~~~~~~
aws-cdk-lib.aws_stepfunctions-README-L589.ts:46:3 - error TS2739: Type 'S3ObjectsItemReaderPath' is missing the following properties from type 'IItemReader': bucket, providePolicyStatements

46   itemReader: new sfn.S3ObjectsItemReaderPath({
     ~~~~~~~~~~
aws-cdk-lib.aws_stepfunctions-README-L589.ts:48:5 - error TS2353: Object literal may only specify known properties, and 'prefix' does not exist in type 'S3ObjectsItemReaderPathProps'.

48     prefix: '$.prefix',
       ~~~~~~
aws-cdk-lib.aws_stepfunctions-README-L589.ts:55:1 - error TS2304: Cannot find name 'distributedMap'.

55 distributedMap.itemProcessor(new sfn.Pass(this, 'Pass State'));
   ~~~~~~~~~~~~~~
[jsii-rosetta] [WARN] 4 diagnostics from assemblies with 'strict' mode on (and 44 more non-strict diagnostics)
```