revert(imagebuilder-alpha): add support for Component Construct (#36104)
Reverts aws/aws-cdk#36006 as it caused JSII errors that is coming from https://github.com/cdklabs/cdk-generate-synthetic-examples
```

@aws-cdk.aws-imagebuilder-alpha.ComponentDocumentPhase-example.ts:9:1 - error TS7005: Variable 'declare' implicitly has an 'any' type.
--
 
9 declare const inputs: any;
~~~~~~~
@aws-cdk.aws-imagebuilder-alpha.ComponentDocumentPhase-example.ts:9:9 - error TS1005: ',' expected.
 
9 declare const inputs: any;
~~~~~
@aws-cdk.aws-imagebuilder-alpha.ComponentDocumentPhase-example.ts:18:4 - error TS1005: '(' expected.
 
18  if: any;
~
@aws-cdk.aws-imagebuilder-alpha.ComponentDocumentPhase-example.ts:18:6 - error TS2693: 'any' only refers to a type, but is being used as a value here.
 
18  if: any;
~~~
@aws-cdk.aws-imagebuilder-alpha.ComponentDocumentPhase-example.ts:27:9 - error TS1109: Expression expected.
 
27     if: if,
~~
@aws-cdk.aws-imagebuilder-alpha.ComponentDocumentPhase-example.ts:27:11 - error TS1005: ':' expected.
 
27     if: if,
~
@aws-cdk.aws-imagebuilder-alpha.ComponentDocumentStep-example.ts:9:1 - error TS7005: Variable 'declare' implicitly has an 'any' type.
 
9 declare const inputs: any;
~~~~~~~
@aws-cdk.aws-imagebuilder-alpha.ComponentDocumentStep-example.ts:9:9 - error TS1005: ',' expected.
 
9 declare const inputs: any;
~~~~~
@aws-cdk.aws-imagebuilder-alpha.ComponentDocumentStep-example.ts:18:4 - error TS1005: '(' expected.
 
18  if: any;
~
@aws-cdk.aws-imagebuilder-alpha.ComponentDocumentStep-example.ts:18:6 - error TS2693: 'any' only refers to a type, but is being used as a value here.
 
18  if: any;
~~~
@aws-cdk.aws-imagebuilder-alpha.ComponentDocumentStep-example.ts:25:7 - error TS1109: Expression expected.
 
25   if: if,
~~
@aws-cdk.aws-imagebuilder-alpha.ComponentDocumentStep-example.ts:25:9 - error TS1005: ':' expected.
 
25   if: if,
~


```