chore(interfaces): submodule names for interface submodules are incorrect (#36036)
### Reason for this change

Go packaging was failing with

```
#STDERR> awsimagebuilder/internal/types.go:4:2: "github.com/aws/aws-cdk-go/awscdk/interfaces/awsimagebuilder" imported and not used
#STDERR> awsimagebuilder/internal/types.go:8:28: undefined: IComponentRef
```

However as it turns out the generated `jsiirc` were using the wrong path. They were missing the required `.` (fullstop) prefix, thus the written package names were not being considered by jsii at all.

For go, we also need to update the interfaces package name to a unique name:

Before:

```
package awsimagebuilder
```

After:

```
package interfacesawsimagebuilder
```

### Description of changes

Use the correct `jsiirc` filename.
Ensure a unique package name for go is used.

### Describe any new or updated permissions being added

n/a

### Description of how you validated changes

Test pipeline is passing. Manually tested go packaging.

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*