Fix requirements file generation with pipenv.
Since 2022.08.13, the deprecated `pipenv lock -r` method of generating
requirements files has been removed in favor of the `pipenv
requirements` command ([Changelog](https://github.com/pypa/pipenv/commit
/1daa4d5d8d810b2466320365c05635fa003d9651)). As such, builds attempted
with a newer version of pipenv fail with the following message:

```
Usage: pipenv lock [OPTIONS]
Try 'pipenv lock -h' for help.

Error: No such option: -r
```

This commit updates the Python Lambda pipenv packaging command to
use the supported `pipenv requirements` method.