fix: update fetchOpenPullRequests method to pass organisation in github action workflow for prioritization (#33073)
### Issue # (if applicable)

N/A

### Reason for this change

`PR Prioritization R5 Check` and` PR Prioritization R2 Check` github action workflow is failing since it is not able to call the graphql api with the repo owner.

```
GraphqlResponseError: Request failed due to following response errors:
 - Variable $owner of type String! was provided invalid value
    at /home/runner/work/_actions/actions/github-script/v7/dist/index.js:6669:[13](https://github.com/aws/aws-cdk/actions/runs/12902208172/job/36014470718#step:3:14)
Error: Unhandled error: GraphqlResponseError: Request failed due to following response errors:
 - Variable $owner of type String! was provided invalid value
```

### Description of changes

R2 and R5 prioritization uses `fetchOpenPullRequests` method that needs to be updated with organisation parameter and query as the `aws-cdk` repo is under `aws` org.

### Describe any new or updated permissions being added

N/A

### Description of how you validated changes

Ran unit test and tested in local repo.

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*