chore: pin aws-sdk-mock to 5.6.0 (#18871)
Version 5.6.1 of aws-sdk-mock introduced new types with the `@ts-ignore`
annotation. The specific type in question is [this one](https://github.com/dwyl/aws-sdk-mock/blob/1a9112b81cef3b0c3fac69d8d3bb1b70c692bf3c/index.d.ts#L60)
For some reason our version of `tsc` is not suppressing the type errors.
I've tested with a newer version of `tsc` and the errors are suppressed.

I'm not sure if this is the right thing to do here, but currently this
causes our upgrade workflow to fail with the error message

```
aws-cdk: ../../node_modules/aws-sdk-mock/index.d.ts(60,90): error TS1110: Type expected.
```


----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*