chore(eslint-plugin): linter chokes on aws-cdk-lib/core import (#26022)
https://github.com/aws/aws-cdk/pull/25802 changed imports in alpha modules from `aws-cdk-lib` to `aws-cdk-lib/core`.

Not sure how that got past the linter in the first place, but my linter is choking on this because `aws-cdk-lib/core` does not have a `package.json`.

```bash
Error: ENOENT: no such file or directory, open '<path>/aws-cdk/packages/aws-cdk-lib/core/package.json'
```

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*