revert: "chore(ground-station): Scaffold AWS Ground Station alpha" (#26704)
Breaks our build. I think it is because there is nothing in `index.ts` but this does not seem like a big enough pr to block a release over, so am reverting.

```
npx tsc
ts-import.ts(18,51): error TS2306: 
File 
'/tmp/tmp.QUQUtYehRM/node_modules/@aws-cdk/aws-groundstation-alpha/lib/index.d.ts'
 is not a module.</span>
```

New packages should always run through the test pipeline before merge.