chore(cli): check for undefined instead of falsey
The return value from `context` is 0 which is falsey. This was causing
pipeline failures with the error

```
Error: Unknown command: context
```