chore(app-staging-synthesizer): use an accepted dotnet namespace/packageId (#25823)
```bash
error CS0118: 'Amazon.CDK.App' is a namespace but is used like a type [/tmp/npm-packXqHZ78/Amazon.CDK.App.Staging.Synthesizer.Alpha
```

This one I put through the test pipeline so it is good to go

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*