fix(cloudformation-diff): move aws-sdk to dependency for cfn-diff to get CFN types resolved in exports (#28768)
Issue still persists after #28680. 
```
node_modules/@aws-cdk/cloudformation-diff/lib/diff-template.d.ts:1:37 - error TS2307: Cannot find module 'aws-sdk' or its corresponding type declarations.

1 import type { CloudFormation } from 'aws-sdk';
                                      ~~~~~~~~~


Found 1 error in node_modules/@aws-cdk/cloudformation-diff/lib/diff-template.d.ts:1
```

Types are still required as a direct dependency in package.json.

Closes #28679 

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*