chore(ecs): add Windows2025 AMI (#34901)
### Issue # (if applicable)
None

### Reason for this change
https://aws.amazon.com/about-aws/whats-new/2025/07/aws-availability-ecs-optimized-windows-server-2025-amis/

### Description of changes
- Add Windows 2025 AMI
- Integ update instance type + image since old ones no longer compatible
<img width="676" alt="Screenshot 2025-07-03 205357" src="https://github.com/user-attachments/assets/f7cb6482-07d9-4061-83f7-82d8cabf955d" />

Error of old image on Windows2025
```console
CannotStartContainerError: Error response from daemon: container f21c7ecd0047ff6ab04059523979ab2c16f20efa2a40a8a68d718fa30131f40c encountered an error during hcs::System::Start: failure in a Windows system call: The container operating system does not match the host operating system.
```

### Describe any new or updated permissions being added




### Description of how you validated changes
Integ

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*