feat(lambda): allow propagating function tags to loggroup (#34556)
### Issue # (if applicable)
same as https://github.com/aws/aws-cdk/pull/34473
Fixes an issue with test. This is resolved if you put the test above the metadata tests. Do not know the root cause. 
```
 FAIL  aws-lambda/test/function.test.ts
  ● Test suite failed to run

    TypeError: this.isNative is not a function

      at Object.CallSiteToString [as toString] (../../node_modules/source-map-support/source-map-support.js:295:12)
      at Function.prepareStackTrace (../../node_modules/source-map-support/source-map-support.js:446:37)
```

Closes #<issue number here>.
https://github.com/aws/aws-cdk/issues/17533
### Reason for this change
Refer README and issue.



### Description of changes
Added a feature flag USE_CDK_MANAGED_LAMBDA_LOGGROUP
Refer README section on ## Customizing Log Group Creation for more details


### Describe any new or updated permissions being added
N/A



### Description of how you validated changes
Unit and integ tests are added to this PR


### Checklist
- [x ] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*