chore: Revert "feat(lambda): provide support for AWS Parameters and Secrets Extension for Lambda" (#25919)
Reverts aws/aws-cdk#25725

This breaks the go build

```


Error: Command (go build -modfile local.go.mod ./...) failed with status 1:
--
3592 | #STDERR> package github.com/aws/aws-cdk-go/awscdk/v2/awsapigateway
3593 | #STDERR>    imports github.com/aws/aws-cdk-go/awscdk/v2/awscognito
3594 | #STDERR>    imports github.com/aws/aws-cdk-go/awscdk/v2/awslambda
3595 | #STDERR>    imports github.com/aws/aws-cdk-go/awscdk/v2/awssecretsmanager
3596 | #STDERR>    imports github.com/aws/aws-cdk-go/awscdk/v2/awslambda: import cycle not allowed
3597 | #STDERR> package github.com/aws/aws-cdk-go/awscdk/v2/awsapigateway
3598 | #STDERR>    imports github.com/aws/aws-cdk-go/awscdk/v2/awscognito
3599 | #STDERR>    imports github.com/aws/aws-cdk-go/awscdk/v2/awslambda
3600 | #STDERR>    imports github.com/aws/aws-cdk-go/awscdk/v2/awssecretsmanager
3601 | #STDERR>    imports github.com/aws/aws-cdk-go/awscdk/v2/awslambda: import cycle not allowed
```


----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*