chore(pkglint): require jsii.dotnet.packageId in package.json (#25816)
Guards against the following error when creating new packages:

```bash
Error: The module @aws-cdk/app-staging-synthesizer-alpha does not have a dotnet.packageId setting
```

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*