chore(efs): use dynamic region and AZ for EFS replication integ test (#37116)
### Issue # (if applicable)
N/A

### Reason for this change
The integ test `integ.efs-filesystem-replication` was failing because it hardcoded `us-east-1` and `us-east-1a` for the one-zone replication configuration. When deployed to other regions, the KMS key (created in the deployment region) didn't match the hardcoded replication target region.

Error: `Failed to create destination file system: Invalid KMS key ID (unexpected region)`

### Description of changes
Changed `oneZoneFileSystem('us-east-1', 'us-east-1a', kmsKey)` to `oneZoneFileSystem(cdk.Aws.REGION, cdk.Stack.of(vpc).availabilityZones[0], kmsKey)` so the replication target matches the deployment region.

### Describe any new or updated permissions being added
N/A

### Description of how you validated changes
```bash
yarn integ test/aws-efs/test/integ.efs-filesystem-replication.js \\
  --disable-update-workflow --update-on-failed --force \\
  --parallel-regions us-east-1 --parallel-regions us-east-2
```
Result: 1 passed, 1 total

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----
*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*