revert(migration): add constructs migration to rewrite script (#15461)
Reverts aws/aws-cdk#14916

This is causing issues in the v2 forward merge.

```
import * as cdk from '@aws-cdk/core';
```

Is being rewritten as `import * as constructs from 'constructs'`, regardless of what from `cdk` we use. In the case of https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/assert-internal/lib/synth-utils.ts for example, we only use `cdk.Stack`, but the imports turn into:

```
import * as fs from 'fs';
import * as path from 'path';
import * as core from 'aws-cdk-lib';
import * as constructs from 'constructs';
import * as cxapi from 'aws-cdk-lib/cx-api';
```

And then TSC complains:

```
@aws-cdk/assert: lib/synth-utils.ts(4,1): error TS6133: 'constructs' is declared but its value is never read.
@aws-cdk/assert: lib/expect.ts(2,1): error TS6133: 'constructs' is declared but its value is never read.
@aws-cdk/assert: jest.ts(2,1): error TS6133: 'constructs' is declared but its value is never read.
@aws-cdk/assert: test/assertions.test.ts(2,13): error TS2300: Duplicate identifier 'constructs'.
@aws-cdk/assert: test/assertions.test.ts(4,13): error TS2300: Duplicate identifier 'constructs'.
```

(Also note `Duplicate identifier` errors)