fix(elasticache-alpha): cannot import Redis 7 serverless cache (#35629)
### Issue # (if applicable)

N/A

### Reason for this change
The `ServerlessCache` class was missing the `CacheEngine.REDIS_7` case in the switch statement that determines the default port for imported caches. 

So importing a Redis 7 serverless cache causes an error:

> ValidationError: Unsupported cache engine: redis_7



### Description of changes
* Added missing `CacheEngine.REDIS_7` case** in the `fromServerlessCacheAttributes`  method's switch statement to ensure Redis 7 caches use the correct default port.
* Add unit tests for all supported versions.



### Describe any new or updated permissions being added
N/A



### Description of how you validated changes
Add unit tests


### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*