chore(lint): replace hard-coded separators with `path.sep` (#26549)
Build on Windows fails due to the hard-coded file path separators (`'/'`) in the eslint rule `invalid-cfn-imports.ts`.
The error message is "no such file or directory, open 'C:\aws-cdk\tools\@aws-cdk\pkglint\bin\pkglint.ts\package.json'" as follows:

```
$ npx lerna run build --scope=aws-cdk-lib
lerna notice cli v7.1.4
lerna notice filter including "aws-cdk-lib"
lerna info filter [ 'aws-cdk-lib' ]

   ×    1/3 dependent project tasks failed (see below)
   √    2/3 dependent project tasks succeeded [0 read from cache]

 ———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————— 


> @aws-cdk/pkglint:build

yarn run v1.22.19
$ tsc -b && eslint . --ext=.ts && chmod +x bin/pkglint
DeprecationWarning: 'originalKeywordKind' has been deprecated since v5.0.0 and will no longer be usable after v5.2.0. Use 'identifierToKeywordKind(identifier)' instead.

Oops! Something went wrong! :(

ESLint: 7.32.0

Error: Error while loading rule '@aws-cdk/invalid-cfn-imports': ENOENT: no such file or directory, open 'C:\aws-cdk\tools\@aws-cdk\pkglint\bin\pkglint.ts\package.json'
Occurred while linting C:\aws-cdk\tools\@aws-cdk\pkglint\bin\pkglint.ts
    at Object.openSync (node:fs:603:3)
    at Object.readFileSync (node:fs:471:35)
    at isAlphaPackage (C:\aws-cdk\tools\@aws-cdk\eslint-plugin\lib\rules\invalid-cfn-imports.js:139:31)
    at currentFileIsInAlphaPackage (C:\aws-cdk\tools\@aws-cdk\eslint-plugin\lib\rules\invalid-cfn-imports.js:110:16)       
    at Object.create (C:\aws-cdk\tools\@aws-cdk\eslint-plugin\lib\rules\invalid-cfn-imports.js:12:10)
    at createRuleListeners (C:\aws-cdk\node_modules\eslint\lib\linter\linter.js:765:21)
    at C:\aws-cdk\node_modules\eslint\lib\linter\linter.js:937:31
    at Array.forEach (<anonymous>)
    at runRules (C:\aws-cdk\node_modules\eslint\lib\linter\linter.js:882:34)
    at Linter._verifyWithoutProcessors (C:\aws-cdk\node_modules\eslint\lib\linter\linter.js:1181:31)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Replace all with `path.sep`, cross-platform separator.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*