fix build errors on generated test
The current generated Go test sample doesn't pass a required argument to `assertions.Template_FromStack`.  A `cdk init --language go` using v2..49.0 generates the error below when running `go test`.  

```bash
$ go test
# goscratch [goscratch.test]
./goscratch_test.go:21:44: not enough arguments in call to assertions.Template_FromStack
        have (awscdk.Stack)
        want (awscdk.Stack, *assertions.TemplateParsingOptions)
FAIL    goscratch [build failed]
```