chore(lambda-destinations): use SQS instead of S3 for onSuccess destination (#37115)
### Issue # (if applicable)
N/A

### Reason for this change
The integ test was failing because S3 buckets are only supported as Lambda on-failure destinations, not on-success. The test incorrectly used `S3Destination` for both `onSuccess` and `onFailure`.

Error: `The provided destination config DestinationConfig(onSuccess=...s3..., onFailure=...s3...) is invalid.`

### Description of changes
Changed the `onSuccess` destination from `S3Destination(successBucket)` to `SqsDestination(successQueue)`. The `onFailure` S3 destination remains unchanged.

### Describe any new or updated permissions being added
N/A (SQS permissions are auto-granted by CDK)

### Description of how you validated changes
```bash
yarn integ test/aws-lambda-destinations/test/integ.destinations.js \\
  --disable-update-workflow --update-on-failed --force \\
  --parallel-regions us-east-1 --parallel-regions us-east-2
```
Result: 1 passed, 1 total

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----
*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*