chore(cli): check for undefined instead of falsey (#18937)
The return value from `context` is 0 which is falsey. This was causing
pipeline failures with the error

```
Error: Unknown command: context
```


----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*