chore: use codecov token instead of OIDC (#32129)
For PR from forks, OIDC doesn't currently work with the latest version of the GitHub Action. 

[Example failure](https://github.com/aws/aws-cdk/actions/runs/11834319601/job/32974759899?pr=32121):

```console
Run codecov/codecov-action@v4
Error: Codecov: Failed to get OIDC token with url: https://codecov.io/. Error message: Unable to get ACTIONS_ID_TOKEN_REQUEST_URL env variable
```

See https://github.com/codecov/codecov-action/issues/1594

Revert back to token until we validate a fix. 

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*