chore: remove `\` that breaks the build (#28752)
The .NET docstring generator fails to escape the stray `\`, leading to a compilation error:

```
#STDOUT> /tmp/npm-packYlIY9W/Amazon.CDK.Lib/Amazon/CDK/AWS/Lambda/FunctionOptions.cs(437,339): error CS1009: Unrecognized escape sequence [/tmp/npm-packYlIY9W/Amazon.CDK.Lib/Amazon.CDK.Lib.csproj]
```

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*