chore: remove regenerate integ-runner steps from the yarn upgrade workflow (#33920)
### Issue # (if applicable)

Closes NA

### Reason for this change

This followup PR to remove integ-runner package related steps from the yarn upgrade workflow. Previous PR #33917 

Currently the workflow is failing at this step with error

```
Run cd packages/@aws-cdk/integ-runner && yarn pkglint
/home/runner/work/_temp/**-[4](https://github.com/aws/aws-cdk/actions/runs/****.sh: line 1: cd: packages/@aws-cdk/integ-runner: No such file or directory
Error: Process completed with exit code 1.
```

### Description of changes

Since integ-runner package is no longer available, this step can be removed from the workflow.

### Describe any new or updated permissions being added

NA

### Description of how you validated changes

Ran yarn install and verified the integ-runner installed version using npx integ-runner --version

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*