chore(iot-actions-alpha): add missing rosetta dependency (#35400)
### Issue # (if applicable)


### Reason for this change

PR builds are failing with `Error: @aws-cdk.aws-iot-alpha-README-L146.ts:9:26 - error TS2307: Cannot find module '@aws-cdk/aws-iot-actions-alpha' or its corresponding type declarations.` lately. This change should fix that issue.

### Description of changes

Added missing `@aws-cdk/aws-iot-actions-alpha` dependency

### Describe any new or updated permissions being added

NA


### Description of how you validated changes
Followed PRs that solved similar issues

### Checklist
- [X] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*