fix(core): core constructs fail with `Error: Cannot find module '../dist/core/<file>.generated'` (#28467)
#28251 added new files to `aws-cdk-lib/core/lib/dist/core` but this path was excluded from the npm package, causing the above error.

This fix includes the generated file into the package.

Closes #28465

Manually tested with a locally build package that includes the fix.
<img width="1449" alt="image" src="https://github.com/aws/aws-cdk/assets/379814/11714c41-edea-403e-9b64-454ba9768c08">

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*