Revert "chore: npm-check-updates && yarn upgrade" (#22052)
Reverts aws/aws-cdk#22036

This dependency upgrade caused the ActionBuildDocs in the v1 pipeline to fail. Reverting first to unblock the release, and then will investigate after. 

The failure error:

```
$ docusaurus-build
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
(node:5184) DeprecationWarning: The endpoint 'yaml/schema' will be removed in a future release.
(Use `node --trace-deprecation ...` to show where the warning was created)
warning package.json: No license field
warning No license field
warning package.json: No license field
Error: Cannot find module 'caniuse-lite/data/features/css-unicode-bidi'
Require stack:
- /tmp/scriptdir/universalsite/docusaurus/website/node_modules/autoprefixer/data/prefixes.js
- /tmp/scriptdir/universalsite/docusaurus/website/node_modules/autoprefixer/lib/autoprefixer.js
- /tmp/scriptdir/universalsite/docusaurus/website/node_modules/docusaurus/lib/server/utils.js
- /tmp/scriptdir/universalsite/docusaurus/website/node_modules/docusaurus/lib/server/blog.js
- /tmp/scriptdir/universalsite/docusaurus/website/node_modules/docusaurus/lib/server/readMetadata.js
- /tmp/scriptdir/universalsite/docusaurus/website/node_modules/docusaurus/lib/write-translations.js
- /tmp/scriptdir/universalsite/docusaurus/website/node_modules/docusaurus/lib/server/generate.js
- /tmp/scriptdir/universalsite/docusaurus/website/node_modules/docusaurus/lib/build-files.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/tmp/scriptdir/universalsite/docusaurus/website/node_modules/autoprefixer/data/prefixes.js:663:12)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module._compile (/tmp/scriptdir/universalsite/docusaurus/website/node_modules/pirates/lib/index.js:136:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.newLoader [as .js] (/tmp/scriptdir/universalsite/docusaurus/website/node_modules/pirates/lib/index.js:141:7)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/tmp/scriptdir/universalsite/docusaurus/website/node_modules/autoprefixer/lib/autoprefixer.js:15:12)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module._compile (/tmp/scriptdir/universalsite/docusaurus/website/node_modules/pirates/lib/index.js:136:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.newLoader [as .js] (/tmp/scriptdir/universalsite/docusaurus/website/node_modules/pirates/lib/index.js:141:7)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/tmp/scriptdir/universalsite/docusaurus/website/node_modules/docusaurus/lib/server/utils.js:8:22)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module._compile (/tmp/scriptdir/universalsite/docusaurus/website/node_modules/pirates/lib/index.js:136:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.newLoader [as .js] (/tmp/scriptdir/universalsite/docusaurus/website/node_modules/pirates/lib/index.js:141:7)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/tmp/scriptdir/universalsite/docusaurus/website/node_modules/docusaurus/lib/server/blog.js:12:29)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module._compile (/tmp/scriptdir/universalsite/docusaurus/website/node_modules/pirates/lib/index.js:136:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.newLoader [as .js] (/tmp/scriptdir/universalsite/docusaurus/website/node_modules/pirates/lib/index.js:141:7)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/tmp/scriptdir/universalsite/docusaurus/website/node_modules/docusaurus/lib/server/readMetadata.js:18:14)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module._compile (/tmp/scriptdir/universalsite/docusaurus/website/node_modules/pirates/lib/index.js:136:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.newLoader [as .js] (/tmp/scriptdir/universalsite/docusaurus/website/node_modules/pirates/lib/index.js:141:7)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/tmp/scriptdir/universalsite/docusaurus/website/node_modules/docusaurus/lib/write-translations.js:34:22)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module._compile (/tmp/scriptdir/universalsite/docusaurus/website/node_modules/pirates/lib/index.js:136:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.newLoader (/tmp/scriptdir/universalsite/docusaurus/website/node_modules/pirates/lib/index.js:141:7)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at _callee$ (/tmp/scriptdir/universalsite/docusaurus/website/node_modules/docusaurus/lib/server/generate.js:14:3)
    at tryCatch (/tmp/scriptdir/universalsite/docusaurus/website/node_modules/docusaurus/lib/server/generate.js:5:2404)
    at Generator._invoke (/tmp/scriptdir/universalsite/docusaurus/website/node_modules/docusaurus/lib/server/generate.js:5:1964)
    at Generator.next (/tmp/scriptdir/universalsite/docusaurus/website/node_modules/docusaurus/lib/server/generate.js:5:3255)
    at asyncGeneratorStep (/tmp/scriptdir/universalsite/docusaurus/website/node_modules/docusaurus/lib/server/generate.js:7:103)
    at _next (/tmp/scriptdir/universalsite/docusaurus/website/node_modules/docusaurus/lib/server/generate.js:9:194)
    at /tmp/scriptdir/universalsite/docusaurus/website/node_modules/docusaurus/lib/server/generate.js:9:364
    at new Promise (<anonymous>)
    at /tmp/scriptdir/universalsite/docusaurus/website/node_modules/docusaurus/lib/server/generate.js:9:97
    at _execute (/tmp/scriptdir/universalsite/docusaurus/website/node_modules/docusaurus/lib/server/generate.js:415:19)
    at execute (/tmp/scriptdir/universalsite/docusaurus/website/node_modules/docusaurus/lib/server/generate.js:18:19)
    at Object.<anonymous> (/tmp/scriptdir/universalsite/docusaurus/website/node_modules/docusaurus/lib/build-files.js:41:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/tmp/scriptdir/universalsite/docusaurus/website/node_modules/autoprefixer/data/prefixes.js',
    '/tmp/scriptdir/universalsite/docusaurus/website/node_modules/autoprefixer/lib/autoprefixer.js',
    '/tmp/scriptdir/universalsite/docusaurus/website/node_modules/docusaurus/lib/server/utils.js',
    '/tmp/scriptdir/universalsite/docusaurus/website/node_modules/docusaurus/lib/server/blog.js',
    '/tmp/scriptdir/universalsite/docusaurus/website/node_modules/docusaurus/lib/server/readMetadata.js',
    '/tmp/scriptdir/universalsite/docusaurus/website/node_modules/docusaurus/lib/write-translations.js',
    '/tmp/scriptdir/universalsite/docusaurus/website/node_modules/docusaurus/lib/server/generate.js',
    '/tmp/scriptdir/universalsite/docusaurus/website/node_modules/docusaurus/lib/build-files.js'
  ]
}
error Command failed with exit code 1.
---------- uni FAILED after 42 seconds ----------
```