chore(aws-cdk-lib): fix error message using deprecated 'name' property (#28275)
Instead of throwing the descriptive error, we throw:

```
ReferenceError: name is not defined
```

We meant to use `submodule.name`, not `name`.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*