chore(cdk-assets): fix test issue
The tests were failing for me on a fresh install with:

```
[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "TypeError: sm.getSecretValue is not a function".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
```

There were two issues:

* `expect(...).resolves` is not a fully-formed assertion. Some assertion
  needs to be made on the result of the resolution, and it nees to be
  awaited.
* Due to the incomplete mocking, `sm.getSecretValue` would be a
  `fn.mock` constructor, instead of an object.

I'm not sure how this ever used to work, but this fixes it.