chore(vpcv2): fix doc issue due to IRoute (#31464)
### Issue # (if applicable)

Closes #NA.

### Reason for this change

Fixes the doc job build failure for python docs failing with the error in main pipeline

```
TypeError: Cannot create a consistent method resolution
order (MRO) for bases IConstruct, IResource, Protocol
```

Issue seemed to have been occured due to IRoute interface extending both IConstruct and IResource, 
we don't need it as `IResource` already extends `IConstruct` and `IConstruct` extends `IDependable`.

### Description of changes

Renamed `IRoute` to `IRouteV2`(as previous release) , we already have an interface in the main lib with name [`IRoute`](https://github.com/aws/aws-cdk/blob/33eea3f7f2e832d63dc2c1823c56f5e235c80076/packages/aws-cdk-lib/aws-apigatewayv2/lib/common/route.ts#L6) for apigateway

### Description of how you validated changes

Deployed in test-pipeline for verification using

```
git fetch origin pull/31464/head
git push -f origin FETCH_HEAD:test-main-pipeline

```



### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*