chore: revert the alpha version computation and change the required version in the sam test (#19573)
The [previous change](https://github.com/aws/aws-cdk/pull/19560) breaks `jsii-pacmak` with the message:

>Error: Unable to map prerelease identifier (in: 2.18.0-rc.0-alpha.0) to python, as sequence ‘0-alpha’ is not an integer

Going for a more conservative solution here: keep the versions as they are and just replace `rc` with `alpha` in the tests that need to install alpha versions.

----

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/master/INTEGRATION_TESTS.md)?
	* [ ] Did you use `cdk-integ` to deploy the infrastructure and generate the snapshot (i.e. `cdk-integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*