chore(kms): overridden validate method must be protected (#9616)
This PR https://github.com/aws/aws-cdk/pull/9269, implemented `validate()` on the  KMS key construct. Since this methods override `Construct` `validate` it must have the same visibility modifier - `protected`. Changing visibility modifier on override methods breaks `jsii-pacmak`, specifically C# packaging.:

```
amazon/CDK/AWS/KMS/Key.cs(97,34): error CS0507: 'Key.Validate()': cannot change access modifiers when overriding 'protected' inherited member 'Construct_.Validate()' [/tmp/npm-packtcwuee/Amazon.CDK.AWS.KMS/Amazon.CDK.AWS.KMS.csproj]
```

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*