fix(cli): SynthUtils is not used (#9836)
unused imports makes the jsii fail because jsii has no chill.

```
.test.ts:1:45 - error TS6133: 'SynthUtils' is declared but its value is never read.
1 import { expect as expectCDK, haveResource, SynthUtils } from '@aws-cdk/assert';
                                              ~~~~~~~~~~
```
----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*