chore: fix C# build
Currently, the generated C# code doesn't compile with this error:

```
error CS0115: 'VpcV2Base._Proxy.Ipv4IpamProvisionedCidrs': no suitable method found to override
```

Most likely because the property on the interface is declared as

```
readonly ipv4IpamProvisionedCidrs?: string[];
```

But the implementor is declared as

```
public readonly ipv4IpamProvisionedCidrs: string[] = [];
```

And the types of those fields are different: `string[] | undefined` vs `string[]`.