fix(iam): override Role.applyRemovalPolicy for customizeRoles (#31652)
### Issue # (if applicable)

Closes #31651 

### Reason for this change



`Role.customizeRoles` throws an Error if there is a construct that calls `applyRemovalPolicy` internally. This means users cannot use with some constructs like `RestApi`.

```
Error: Cannot apply RemovalPolicy: no child or not a CfnResource. Apply the removal policy on the CfnResource directly.
```

This can be reproduced with:

```typescript
const app = new App();
Role.customizeRoles(app);
const stack = new Stack(app, 'Stack');
new RestApi(stack, 'RestApi');
```

Or explicitly:
 
```typescript
const app = new App();
Role.customizeRoles(app);
const stack = new Stack(app, 'Stack');
const role = new Role(stack, 'Role', { assumedBy: new ServicePrincipal('sns.amazonaws.com') });
role.applyRemovalPolicy(RemovalPolicy.DESTROY);
```

### Description of changes



While it might be possible to fix `RestApi`, there could be other constructs within aws-cdk-lib that also call `Role.applyRemovalPolicy`. Moreover, it's nearly impossible to make library users aware of this.

Since `Role` implements the `IResource` interface, it has the responsibility to respond to the `applyRemovalPolicy` call. Therefore, I think it would be good to override `applyRemovalPolicy` in the `Role` class.

### Description of how you validated changes



Fixed the existing unit test to change behavior.

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*