fix(cloudwatch-actions): multiple alarms with LambdaAction for the same Lambda fail (under feature flag) (#28712)
Multiple alarms with LambdaAction for the same Lambda fail, because of the same logical IDs for generated lambda permissions.

```ts
alarmConcurrentLambdasMaximumReached.addAlarmAction(new awsCloudWatchActions.LambdaAction(lambda));
alarmRdsCpuUtilizationMaximumReached.addAlarmAction(new awsCloudWatchActions.LambdaAction(lambda));
```

```
throw new Error(`There is already a Construct with name '${childName}' in ${typeName}${name.length > 0 ? ' [' + name + ']' : ''}`);
            ^
Error: There is already a Construct with name 'AlarmPermission' in NodejsFunction [...]
```

Since the existing logical IDs would change, I implemented this with a feature flag.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*