chore: fix workflows (#33457)
### Issue # (if applicable)

n/a

### Reason for this change

Checking out the `head.sha` puts us into 'detached HEAD' state

```
You are in 'detached HEAD' state. You can look around, make experimental
  changes and commit them, and you can discard any commits you make in this
  state without impacting any branches by switching back to a branch.
```

so the workflow will fail during the commit/push step:

```
Run git config --global user.name 'aws-cdk-automation'
[detached HEAD 0364b3fc] chore: update analytics metadata blueprints
 3 files changed, 121 insertions(+), 121 deletions(-)
error: src refspec bump/2.179.0 does not match any
error: failed to push some refs to 'https://github.com/aws/aws-cdk'
Error: Process completed with exit code 1.
```

### Description of changes

Checkout the branch head ref just before we commit changes in the workflow.


### Describe any new or updated permissions being added

n/a


### Description of how you validated changes

Tested on release branch, workflow successfully [ran](https://github.com/aws/aws-cdk/actions/workflows/analytics-metadata-updater.yml).

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*